### ISSUE TITLE
Lambda Runtime Python 2.7 EOL

### ISSUE THREAD

**Issue by tylangesmith** [awslabs/aws-cloudendure-migration-factory-solution#3]
This solution implements functions which use the `python2.7` runtime. This is becoming EOL on July 15th. Let's update the version to that latest supported python version.

https://aws.amazon.com/blogs/compute/announcing-end-of-support-for-python-2-7-in-aws-lambda/

**Comment by wallylv** [comment]
Thanks for the heads-up, we have updated the Lambda function to use Python 3.7 in the latest release today
